[package]
name = "tpaste-client"
version = "0.2.0"
edition = "2024"

[dependencies]
reqwest={version = "0.12", default-features=false, features=["blocking","json","rustls-tls-native-roots"]}
anyhow = "1"
serde = { version = "1", features = ["derive"] }

tpaste-shared={path="../shared"}